#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

# This script now only generates UI font IDs.
# Reader font IDs are deterministic constants defined directly in fontIds.h.

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "// Reader font IDs are deterministic constants -- edit them by hand in fontIds.h."
echo "#pragma once"
echo ""

echo "// Reader font IDs: deterministic constants (family * 100 + size)."
echo "// These differ from the old hash-based IDs, which intentionally invalidates"
echo "// stale EPUB section caches from before the dynamic font rasterization change."
echo "#define BOOKERLY_12_FONT_ID 112"
echo "#define BOOKERLY_14_FONT_ID 114"
echo "#define BOOKERLY_16_FONT_ID 116"
echo "#define BOOKERLY_18_FONT_ID 118"
echo ""
echo "#define NOTOSANS_12_FONT_ID 212"
echo "#define NOTOSANS_14_FONT_ID 214"
echo "#define NOTOSANS_16_FONT_ID 216"
echo "#define NOTOSANS_18_FONT_ID 218"
echo ""
echo "#define OPENDYSLEXIC_8_FONT_ID 308"
echo "#define OPENDYSLEXIC_10_FONT_ID 310"
echo "#define OPENDYSLEXIC_12_FONT_ID 312"
echo "#define OPENDYSLEXIC_14_FONT_ID 314"
echo ""

echo "// UI font IDs: generated from file hashes"

echo "#define UI_10_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./ubuntu_10_regular.h",
  "./ubuntu_10_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./ubuntu_12_regular.h",
  "./ubuntu_12_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define SMALL_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_8_regular.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"
