#!/usr/bin/env python3
"""Convert a TTF/OTF font file to a C header with a const uint8_t[] array."""

import sys
import os
import argparse


def chunks(data, n):
    for i in range(0, len(data), n):
        yield data[i:i + n]


def main():
    parser = argparse.ArgumentParser(
        description="Convert a TTF/OTF file to a C header with embedded byte array."
    )
    parser.add_argument("name", help="C identifier name for the array (e.g. bookerly_regular_ttf)")
    parser.add_argument("input", help="Path to the TTF/OTF file")
    args = parser.parse_args()

    with open(args.input, "rb") as f:
        data = f.read()

    print(f"/**")
    print(f" * Embedded font: {os.path.basename(args.input)}")
    print(f" * Size: {len(data)} bytes")
    print(f" * Generated by ttf2header.py")
    print(f" */")
    print(f"#pragma once")
    print(f"#include <cstdint>")
    print(f"#include <cstddef>")
    print(f"")
    print(f"static const uint8_t {args.name}[] = {{")
    for chunk in chunks(data, 16):
        print("    " + " ".join(f"0x{b:02X}," for b in chunk))
    print(f"}};")
    print(f"")
    print(f"static const size_t {args.name}_size = {len(data)};")


if __name__ == "__main__":
    main()
