// Reader font IDs: deterministic constants (family * 100 + size).
// These differ from the old hash-based IDs, which intentionally invalidates
// stale EPUB section caches from before the dynamic font rasterization change.
#pragma once

#define BOOKERLY_12_FONT_ID 112
#define BOOKERLY_14_FONT_ID 114
#define BOOKERLY_16_FONT_ID 116
#define BOOKERLY_18_FONT_ID 118

#define NOTOSANS_12_FONT_ID 212
#define NOTOSANS_14_FONT_ID 214
#define NOTOSANS_16_FONT_ID 216
#define NOTOSANS_18_FONT_ID 218

#define OPENDYSLEXIC_8_FONT_ID 308
#define OPENDYSLEXIC_10_FONT_ID 310
#define OPENDYSLEXIC_12_FONT_ID 312
#define OPENDYSLEXIC_14_FONT_ID 314

// UI font IDs: still generated by ./lib/EpdFont/scripts/build-font-ids.sh
#define UI_10_FONT_ID (-2080153638)
#define UI_12_FONT_ID (-1282389375)
#define SMALL_FONT_ID (-1085350703)
